import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { webcrypto } from 'node:crypto';
const entries=new Map();
let full=false;
const storage={getItem:k=>entries.get(k)||null,setItem:(k,v)=>{if(full)throw new Error('Speicher voll');entries.set(k,String(v));}};
function context() {
  const ctx=vm.createContext({console,JSON,Date,Math,Set,Map,Promise,URL,Intl,crypto:webcrypto,localStorage:storage});
  for(const file of ['js/trip-store.js','js/trip/repository.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
  return ctx;
}
const ctx=context();
ctx.TripStore.init([{dayNumber:1,date:'2027-03-21',title:'Wien',activities:[],sights:[]}]);
const repo=ctx.createTripRepository(ctx.TripStore,storage,{tripMeta:{id:'test-trip',title:'Testreise'}});
await repo.init();
const first=repo.getDays()[0];
const stop=repo.createStop(first.id,{title:'Flughafen',type:'flight',transportMode:'plane',region:'Wien',locationName:'Flughafen Wien',latitude:48.11,longitude:16.57,startTime:'09:00',endTime:'10:00',notes:'Reisepass',cost:12,currency:'EUR',bookingReference:'REF-1',bookingUrl:'https://example.com'});
assert.equal(stop.dayId,first.id);assert.equal(stop.tripId,'test-trip');assert.equal(stop.order,0);assert.ok(stop.createdAt);
const secondStop=repo.createStop(first.id,{title:'Ankunft',type:'flight',transportMode:'plane',region:'Sydney',locationName:'Sydney Airport',latitude:-33.94,longitude:151.17});
repo.reorderStops(first.id,[secondStop.id,stop.id]);assert.equal(repo.getStops(first.id)[0].id,secondStop.id);
assert.throws(()=>repo.reorderStops(first.id,[stop.id,stop.id]),/Reihenfolge/);
repo.updateStop(stop.id,{title:'Airport Wien',endTime:'11:00',cost:15});assert.equal(repo.getStop(stop.id).cost,15);assert.equal(repo.getStop(stop.id).notes,'Reisepass');
assert.throws(()=>repo.updateStop(stop.id,{latitude:100}),/Koordinaten/);
assert.throws(()=>repo.updateStop(stop.id,{bookingUrl:'javascript:alert(1)'}),/Links/);
assert.throws(()=>repo.updateStop(stop.id,{endTime:'08:00'}),/Endzeit/);
assert.throws(()=>repo.updateStop(stop.id,{latitude:null,longitude:14}),/gemeinsam/);
const secondDay=repo.createDay({title:'Sydney',date:'2027-03-22'});
assert.throws(()=>repo.createDay({title:'Invalid',date:'2027-02-30'}),/Datum/);
repo.updateDay(secondDay.id,{title:'Sydney',date:'2027-03-22',order:0});assert.equal(repo.getDays()[0].id,secondDay.id);
repo.updateDay(secondDay.id,{title:'Sydney',date:'2027-03-22',order:1});assert.equal(repo.getDays()[1].id,secondDay.id);
repo.updateStop(stop.id,{dayId:secondDay.id});assert.equal(repo.getStops(first.id).length,1);assert.equal(repo.getStops(secondDay.id).length,1);
repo.updateDay(secondDay.id,{title:'Sydney City',date:'2027-03-23'});assert.equal(repo.getDay(secondDay.id).date,'2027-03-23');
const duplicate=repo.duplicateDay(secondDay.id);assert.notEqual(repo.getStops(duplicate.id)[0].id,stop.id);assert.equal(repo.getStops(duplicate.id)[0].dayId,duplicate.id);
repo.reorderDays([duplicate.id,first.id,secondDay.id]);assert.equal(repo.getDays()[0].id,duplicate.id);
const snapshot=JSON.stringify(repo.getDays());full=true;
assert.throws(()=>repo.deleteStop(stop.id),/Speicher voll/);assert.equal(JSON.stringify(repo.getDays()),snapshot);full=false;
const reload=context();await reload.TripStore.load();const loaded=reload.createTripRepository(reload.TripStore,storage,{tripMeta:{id:'test-trip',title:'Testreise'}});await loaded.init();
assert.equal(JSON.stringify(loaded.getDays()),snapshot);assert.equal(loaded.getStop(stop.id).bookingReference,'REF-1');
repo.deleteStop(stop.id);assert.equal(repo.getStop(stop.id),null);
repo.deleteDay(duplicate.id);assert.equal(repo.getStops().length,1);
repo.deleteDay(first.id);repo.deleteDay(secondDay.id);assert.equal(repo.getDays().length,0);
const empty=context();await empty.TripStore.load();assert.equal(empty.TripStore.getDays().length,0,'empty itinerary must survive reload');
repo.updateTrip({title:'Neue Bezeichnung',currency:'AUD'});assert.equal(repo.getTrip().title,'Neue Bezeichnung');
repo.deleteTrip();assert.equal(repo.getTrip(),null);repo.createTrip({title:'Neue Reise'});assert.ok(repo.getTrip().id);
// Existing sights become real editable stops once; deleting one must never resurrect it on reload.
entries.clear();const migration=context();migration.TripStore.init([{dayNumber:1,date:'2027-01-01',title:'Hafen',activities:[{title:'Besuch Sydney Opera House',time:'09:00'}],sights:[{id:'opera',name:'Sydney Opera House',coords:[-33.857,151.215]}]}]);
const migrated=migration.createTripRepository(migration.TripStore,storage,{tripMeta:{id:'trip',title:'Sydney'}});await migrated.init();assert.equal(migrated.getStops().length,1);assert.equal(migrated.getStops()[0].latitude,-33.857);
migrated.deleteStop(migrated.getStops()[0].id);const migrationReload=context();await migrationReload.TripStore.load();const noResurrection=migrationReload.createTripRepository(migrationReload.TripStore,storage,{tripMeta:{id:'trip',title:'Sydney'}});await noResurrection.init();assert.equal(noResurrection.getStops().length,0);
console.log('Trip repository: CRUD, migration, persistence, validation, reordering and atomic failure checks passed.');
