import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const e=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const ctx=vm.createContext({window:{TripModel:{escape:e,dateLabel:v=>v},ManagementModel:{CATEGORIES:{transport:'Transport',food:'Essen'},STATUS:{paid:'Bezahlt'},EXP_STATUS:{paid:'Bezahlt'}}},Intl,console,Blob});
for(const file of ['js/management/ui.js','js/management/finance.js','js/journal/repository.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);
const F=ctx.window.FinanceView,U=ctx.window.ManagementUI;
const summary={totalBudget:800,spent:400,remaining:400,pending:80,currency:'EUR',excluded:1,categories:[{category:'transport',amount:300},{category:'food',amount:100}]};
const repo={summary:()=>summary,trip:{getDays:()=>[]}};
assert.equal(F.amount(400),100);assert.equal(F.divisor(),4);
let html=F.render(repo,[]);
assert.match(html,/stroke-dasharray="75 25"/);assert.match(html,/stroke-dasharray="25 75"/);
assert.ok(html.includes(U.money(100,'EUR')));
const expense={id:'a',title:'Test',date:'2027-03-21',category:'food',amount:80,currency:'AUD',status:'paid'};
assert.ok(U.list('expense',[expense],repo,F.divisor()).includes(U.money(20,'AUD')));
F.setMode('group');assert.equal(F.amount(400),400);assert.equal(F.divisor(),1);
assert.ok(F.render(repo,[]).includes(U.money(400,'EUR')));
assert.ok(U.list('expense',[expense],repo,F.divisor()).includes(U.money(80,'AUD')));
assert.equal(summary.spent,400);assert.equal(expense.amount,80);
F.setMode('invalid');assert.equal(F.getMode(),'group');
const zero={...summary,categories:[{category:'food',amount:0}],spent:0,totalBudget:0};
assert.ok(!F.render({summary:()=>zero},[]).includes('NaN'));
const R=ctx.window.JournalRepository;
assert.equal(R.validate({day:'20',location:' Sydney ',note:' Test '}).location,'Sydney');
for(const day of [-1,21,1.2,'bad'])assert.throws(()=>R.validate({day}));
assert.throws(()=>R.validate({day:1,note:'x'.repeat(1001)}));
const data={'aus_roadtrip_photos_2027':JSON.stringify([{id:1,dayNum:3,url:'https://example.com/photo.jpg',caption:'Foto-Notiz'}]),'aus_roadtrip_journal_2027':JSON.stringify({2:{day:2,title:'Ankunft',text:'Nicht verlieren',notes:'Alte Notiz',highlights:['Hafen'],photoUrls:['https://example.com/a.jpg','https://example.com/b.jpg']}})};
const migrated=R.legacyEntries({getItem:key=>data[key]??null});
assert.equal(migrated.length,2);assert.ok(migrated[1].note.includes('Nicht verlieren'));assert.ok(migrated[1].note.includes('Hafen'));assert.equal(migrated[1].legacyUrls.length,2);
assert.throws(()=>R.legacyEntries({getItem:()=>'{invalid'}));
const unsafe=R.legacyEntries({getItem:key=>key.includes('photos')?'[{"url":"javascript:alert(1)"}]':'{}'});
assert.equal(unsafe[0].url,'');
const index=fs.readFileSync('index.html','utf8');assert.ok(!index.includes('manage-drone-map'));assert.ok(!index.includes('photo-modal-backdrop'));assert.ok(index.includes('memory-upload-form'));
console.log('Finance/journal: 1/4 display without data mutation, foreign-currency rows, SVG percentages/zero state, validation and lossless legacy text/link migration passed.');
// Exercise the real IndexedDB repository with atomic transaction behavior.
const stores=new Map();let initialized=false,failWrite=false,nextId=0;
const database={createObjectStore(name){stores.set(name,new Map());},close(){},transaction(names,mode){
 const draft=new Map(names.map(name=>[name,new Map(stores.get(name))]));let aborted=false;
 const tx={objectStore(name){const data=draft.get(name);return {get:key=>({result:data.get(key)}),getAll:()=>({result:[...data.values()]}),put(value,key){if(failWrite){aborted=true;return;}data.set(key??value.id,value);},add(value){if(failWrite){aborted=true;return;}data.set(value.id,value);}};},abort(){aborted=true;}};
 queueMicrotask(()=>{if(aborted){tx.onabort?.();return;}if(mode==='readwrite')for(const [name,data] of draft)stores.set(name,data);tx.oncomplete?.();});return tx;
}};
ctx.window.indexedDB={open(){const request={result:database};queueMicrotask(()=>{if(!initialized){request.onupgradeneeded();initialized=true;}request.onsuccess();});return request;}};
ctx.window.localStorage={getItem:key=>data[key]??null};ctx.window.crypto={randomUUID:()=> 'test-'+(++nextId)};
const repository=await R.open();assert.equal((await repository.list()).length,2);
await repository.add({day:20,location:'Test',note:'Gespeichert'},[{blob:new Blob(['photo']),name:'test.jpg'}]);
assert.equal((await repository.list()).length,3);
const reopened=await R.open();assert.equal((await reopened.list()).length,3,'Migration must not repeat');
failWrite=true;
await assert.rejects(()=>repository.add({day:1},[{blob:new Blob(['photo']),name:'failure.jpg'}]));
assert.equal((await repository.list()).length,3,'Failed upload must not create partial records');
assert.ok(data['aus_roadtrip_journal_2027'].includes('Nicht verlieren'),'Original legacy storage remains intact');
console.log('Journal persistence: atomic upload, repeat-safe migration, reopen and write failure checks passed.');
