import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
let calls=0;
const context=vm.createContext({console,crypto:webcrypto,TextEncoder,fetch:()=>{calls++;throw new Error('No server allowed');}});
context.window=context;
vm.runInContext(fs.readFileSync('js/session.js','utf8'),context);
const first=await context.AppSession.restore(), second=await context.AppSession.restore();
assert.equal(calls,0);assert.equal(first.key.extractable,false);assert.equal(first.syncTopic,second.syncTopic);
assert.match(first.resources.photos,/^https:/);
const iv=webcrypto.getRandomValues(new Uint8Array(12));
const encrypted=await webcrypto.subtle.encrypt({name:'AES-GCM',iv},first.key,new TextEncoder().encode('group-state'));
const plain=await webcrypto.subtle.decrypt({name:'AES-GCM',iv},second.key,encrypted);
assert.equal(new TextDecoder().decode(plain),'group-state');
console.log('Static bootstrap: no session API, public resource links and compatible group encryption passed.');
