/* No simulated airspace: replace the provider only with a verified data source. */
(function(root){
'use strict';const M=root.TripModel,e=M.escape;
root.FlightZoneProvider={async load(){return {available:false,zones:[],source:null,message:'Keine verlässliche Flugzonenquelle angebunden. Diese Karte gibt keine Flugfreigabe.'};}};
root.createDroneMap=function(container,repo,onSelect,onError,onStatus){
 let map,spots,route,zones,groups=[],selection=null,routeShown=true,spotsShown=true,favorites=false;
 function init(){if(map)return true;if(!root.L){onError(new Error('Karte konnte nicht geladen werden.'));return false;}map=L.map(container,{zoomControl:false,scrollWheelZoom:true}).setView([-27,140],4);const tiles=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);tiles.on('loading',()=>onStatus('Karte wird geladen …'));tiles.on('load',()=>onStatus(''));tiles.on('tileerror',()=>onStatus('Einzelne Kartenkacheln sind nicht verfügbar.'));spots=L.layerGroup().addTo(map);route=L.layerGroup().addTo(map);zones=L.layerGroup().addTo(map);return true;}
 function render(){if(!init())return;spots.clearLayers();route.clearLayers();groups=[];
  if(routeShown)repo.trip.getDays().forEach(d=>{const pts=repo.trip.getStops(d.id).filter(M.coords);pts.forEach(s=>L.circleMarker([s.latitude,s.longitude],{radius:4,color:'#667b86',fillOpacity:.7,weight:1}).bindTooltip(e(s.title)).addTo(route));if(pts.length>1)L.polyline(pts.map(s=>[s.latitude,s.longitude]),{color:'#77938f',weight:2,opacity:.45,dashArray:'5 8'}).addTo(route);groups.push(...pts.map(s=>[s.latitude,s.longitude]));});
  if(spotsShown)repo.get('drone').filter(s=>!favorites||s.favorite).forEach(s=>{const marker=L.marker([s.latitude,s.longitude],{draggable:true,icon:L.divIcon({className:'trip-marker-wrap',html:`<span class="manage-drone-marker ${selection===s.id?'is-active':''}"><i class="fa-solid fa-${s.favorite?'star':'location-dot'}" aria-hidden="true"></i></span>`,iconSize:[38,38],iconAnchor:[19,19]})}).addTo(spots).bindTooltip(e(s.title));marker.getElement().setAttribute('aria-label',s.title+' – Drohnen-Spot');marker.on('click',()=>onSelect(s.id));marker.on('dragend',()=>{const pos=marker.getLatLng();try{repo.save('drone',{...s,latitude:pos.lat,longitude:pos.lng},s.id);}catch(err){marker.setLatLng([s.latitude,s.longitude]);onError(err);}});groups.push([s.latitude,s.longitude]);});
 }
 function fit(){if(!map)return;if(groups.length)map.fitBounds(L.latLngBounds(groups),{paddingTopLeft:[35,25],paddingBottomRight:[innerWidth>760?370:35,50],maxZoom:13});else map.setView([-27,140],4);}
 return {render,fit,resize(){if(init()){map.invalidateSize();}},zoom(n){if(init())map.setZoom(map.getZoom()+n);},focus(id){selection=id;const s=repo.get('drone').find(x=>x.id===id);render();if(s)map.setView([s.latitude,s.longitude],Math.max(map.getZoom(),12));},setLayer(key,value){if(key==='route')routeShown=value;if(key==='spots')spotsShown=value;if(key==='favorites')favorites=value;if(key==='zones'&&map){if(value)zones.addTo(map);else map.removeLayer(zones);}render();},async loadZones(){const result=await root.FlightZoneProvider.load({tripId:repo.trip.getTrip()?.id});if(init())zones.clearLayers();if(result.available&&result.zones?.length){result.zones.forEach(z=>L.geoJSON(z.geometry,{style:{color:{restricted:'#b57964',controlled:'#a99a61',allowed:'#6e9d86',unknown:'#8c9399'}[z.type]||'#8c9399',weight:1,fillOpacity:.12}}).addTo(zones));}return result;}};
};
}(window));
