(function(root){
'use strict';
const M=root.TripModel,N=root.ManagementModel,U=root.ManagementUI,e=M.escape;
function createEditor(repo,onSaved){
 const dialog=document.getElementById('manage-editor'),form=document.getElementById('manage-form'),fields=document.getElementById('manage-fields'),error=document.getElementById('manage-error'),save=document.getElementById('manage-save'),del=document.getElementById('manage-delete'),detailActions=document.getElementById('manage-detail-actions');let kind,item={},busy=false,opener;
 const input=(name,label,type='text',wide=false,attrs='')=>`<label class="${wide?'trip-field-wide':''}">${label}<input name="${name}" type="${type}" value="${e(item[name]??'')}" ${attrs}></label>`;
 const area=(name,label)=>`<label class="trip-field-wide">${label}<textarea name="${name}">${e(item[name]||'')}</textarea></label>`;
 const select=(name,label,choices)=>`<label>${label}<select name="${name}" aria-label="${e(label)}">${Object.entries(choices).map(([k,v])=>`<option value="${e(k)}" ${String(item[name]||'')===k?'selected':''}>${e(v)}</option>`).join('')}</select></label>`;
 function relations(){return select('dayId','Reisetag',{'':'Noch nicht zugeordnet',...Object.fromEntries(repo.trip.getDays().map((d,i)=>[d.id,'Tag '+(i+1)+' · '+d.title]))})+select('stopId','Stopp verknüpfen',{'':'Kein Stopp',...Object.fromEntries(repo.trip.getStops().map(s=>[s.id,s.title]))});}
 function time(){return input('startTime','Startzeit','time')+input('endTime','Endzeit','time');}
 function renderFields(){
  if(kind==='budget')return input('totalBudget','Gesamtbudget der Reisegruppe','number',false,'min="0" step="0.01" required')+input('currency','Währung','text',false,'required maxlength="3"');
  let html=input('title',kind==='drone'?'Spot-Name':'Titel','text',true,'required maxlength="200"');
  if(kind==='expense')html+='<p class="trip-field-wide trip-field-hint">Hier immer den vollständigen Betrag der Reisegruppe eingeben. Der Personen-Umschalter teilt nur die Anzeige.</p>'+select('category','Kategorie',N.CATEGORIES)+select('status','Zahlungsstatus',N.EXP_STATUS)+input('amount','Betrag für 4 Personen','number',false,'min="0" step="0.01" required')+input('currency','Währung','text',false,'required maxlength="3"')+input('date','Datum','date',false,'required')+relations()+select('bookingId','Buchung verknüpfen',{'':'Keine Buchung',...Object.fromEntries(repo.get('booking').map(b=>[b.id,b.title]))});
  if(kind==='activity')html+=select('category','Kategorie',N.ACTIVITY_CATEGORIES)+select('bookingStatus','Buchungsstatus',N.STATUS)+relations()+input('date','Datum (für unzugeordnete Ausflüge)','date')+time()+input('locationName','Ort','text',true)+input('address','Adresse','text',true)+input('latitude','Breitengrad','number',false,'step="any" min="-90" max="90"')+input('longitude','Längengrad','number',false,'step="any" min="-180" max="180"')+area('description','Beschreibung')+input('image','Bild-URL','url',true)+input('price','Preis','number',false,'min="0" step="0.01"')+input('currency','Währung','text',false,'maxlength="3" required')+input('website','Website','url',true)+`<p class="trip-field-wide trip-field-hint">Zugeordnete Ausflüge sind Stops im Reiseplan. Änderungen gelten in beiden Bereichen. Beim Verknüpfen eines bestehenden Stops übernimmt er diese Ausflugsdaten.</p>`;
  if(kind==='booking')html+=select('type','Buchungstyp',N.BOOKING_TYPES)+select('status','Status',N.STATUS)+input('provider','Anbieter','text',true)+input('date','Datum / Check-in','date',false,'required')+input('startTime','Uhrzeit / Check-in','time')+relations()+input('location','Ort / Adresse','text',true)+input('bookingReference','Buchungsreferenz')+input('price','Preis','number',false,'min="0" step="0.01"')+select('priceType','Preisberechnung',N.PRICE_TYPES||{per_person:'Pro Person',total:'Gesamtkosten',two_persons:'Für 2 Personen'})+input('currency','Währung','text',false,'required maxlength="3"')+`<output id="manage-price-preview" class="trip-field-wide glass-price-preview" aria-live="polite"></output>`+input('url','Buchungslink','url',true)+`<details class="trip-field-wide manage-extra"><summary>Flug-, Hotel- und Transportdetails</summary><div>${input('departureAirport','Abflughafen')+input('arrivalAirport','Zielflughafen')+input('flightNumber','Flug- / Zugnummer')+input('arrivalTime','Ankunftszeit','time')+input('checkOut','Check-out','date')+input('room','Zimmer / Fahrzeug')+input('guests','Gäste','number',false,'min="1" step="1"')+input('attachmentUrl','Unterlagen-Link','url',true)}</div></details>`;
  if(kind==='drone')html+=select('category','Kategorie',{landscape:'Landschaft',urban:'Stadt',coast:'Küste',other:'Sonstiges'})+input('date','Geplanter Besuch','date')+relations()+input('latitude','Breitengrad','number',false,'step="any" min="-90" max="90" required')+input('longitude','Längengrad','number',false,'step="any" min="-180" max="180" required')+input('image','Bild-URL','url',true)+`<label class="manage-check trip-field-wide"><input name="favorite" type="checkbox" ${item.favorite?'checked':''}> Als Favorit speichern</label>`;
  if(kind==='document')html+=select('category','Kategorie',N.DOCUMENT_CATEGORIES)+input('url','Dokument-Link','url',true,'required')+relations()+`<p class="trip-field-wide trip-field-hint">Hier werden nur Links gespeichert. Verwende für sensible Unterlagen einen geschützten Speicher.</p>`;
  return html+area('notes','Notizen');
 }
 function open(type,entity={},detail=false){kind=type;item={currency:repo.getBudget().currency,date:repo.trip.getDays()[0]?.date||new Date().toISOString().slice(0,10),category:type==='expense'?'other':'sightseeing',type:'other',priceType:'total',status:type==='expense'?'pending':'pending',bookingStatus:'pending',...entity};opener=document.activeElement;error.textContent='';document.getElementById('manage-editor-title').textContent=type==='budget'?'Budget bearbeiten':detail?item.title:({expense:'Ausgabe',activity:'Ausflug',booking:'Buchung',drone:'Drohnen-Spot',document:'Dokument'}[type]+(item.id?' bearbeiten':' hinzufügen'));detailActions.hidden=!detail;save.hidden=detail;del.hidden=detail||!item.id||type==='budget';fields.innerHTML=detail?renderDetail():renderFields();form.dataset.mode=detail?'detail':'edit';lockRelations();updatePricePreview();if(!dialog.open)dialog.showModal();}
 function updatePricePreview(){
  const output=fields.querySelector('#manage-price-preview');if(!output)return;
  const price=fields.querySelector('[name=price]').value;
  if(price===''){output.textContent='Preis für die Reisegruppe mit 4 Personen eingeben.';return;}
  const value=Number(price),mode=fields.querySelector('[name=priceType]').value,total=value*(mode==='per_person'?4:mode==='two_persons'?2:1),currency=fields.querySelector('[name=currency]').value.toUpperCase();
  try{output.textContent='Gesamt: '+U.money(total,currency)+' · '+U.money(total/4,currency)+' p. P. (4 Personen)';}catch{output.textContent='Bitte eine gültige Währung eingeben.';}
 }
 fields.addEventListener('input',updatePricePreview);
 fields.addEventListener('change',updatePricePreview);
 function lockRelations(){if(kind==='activity'&&item.stopId&&form.dataset.mode==='edit'){const stop=fields.querySelector('[name=stopId]'),day=fields.querySelector('[name=dayId]');if(stop)stop.disabled=true;if(day)day.options[0].disabled=true;}}
 function renderDetail(){const known=[['date','Datum'],['startTime','Startzeit'],['endTime','Endzeit'],['locationName','Ort'],['location','Ort'],['address','Adresse'],['departureAirport','Abflug'],['arrivalAirport','Ankunft'],['flightNumber','Flug / Zug'],['arrivalTime','Ankunftszeit'],['checkOut','Check-out'],['room','Zimmer / Fahrzeug'],['guests','Gäste'],['bookingReference','Referenz'],['description','Beschreibung'],['notes','Notizen']];let priceHtml='';if(item.currency&&(item.amount??item.price)!=null){if(kind==='booking'){const rawPrice=item.price??0;const type=item.priceType||'total';const total=item.totalAmount??(type==='per_person'?rawPrice*4:(type==='two_persons'?rawPrice*2:rawPrice));const perPerson=item.perPersonAmount??(total/4);priceHtml=`<div class="glass-detail-price"><h3 class="manage-detail-price-prominent">${e(U.money(total,item.currency))}</h3><span class="glass-pill">(${e(U.money(perPerson,item.currency))} p. P.)</span></div>`;}else{priceHtml=`<h3>${e(U.money(kind==='expense'?root.FinanceView.amount(item.amount):item.price,item.currency))}</h3>`;}}return `<div class="manage-detail trip-field-wide">${M.safeUrl(item.image)?`<img src="${e(item.image)}" alt="">`:''}${priceHtml}${U.badge(kind==='activity'?item.bookingStatus:item.status,kind==='expense'?N.EXP_STATUS:N.STATUS)}${item.relationMissing?'<p class="manage-notice">Eine Verknüpfung ist nicht mehr vorhanden. Du kannst sie beim Bearbeiten neu zuordnen.</p>':''}${U.dayLink(item,repo)}${known.filter(([key])=>item[key]).map(([key,label])=>`<div><span>${label}</span><p>${e(key==='date'?M.dateLabel(item[key]):item[key])}</p></div>`).join('')}${M.coords(item)?`<p>${item.latitude.toFixed(5)}, ${item.longitude.toFixed(5)}</p>`:''}${['website','url','attachmentUrl'].filter(k=>M.safeUrl(item[k])).map(k=>`<a href="${e(item[k])}" target="_blank" rel="noopener noreferrer">${k==='attachmentUrl'?'Unterlagen öffnen':'Website öffnen'} ↗</a>`).join('')}</div>`;}
 async function perform(fn){if(busy)return;busy=true;form.setAttribute('aria-busy','true');save.textContent='Wird gespeichert …';form.querySelectorAll('button,input,textarea,select').forEach(el=>el.disabled=true);document.getElementById('manage-close').disabled=true;try{const result=await fn();dialog.close();onSaved?.(result,kind);const live=document.getElementById('manage-live');live.classList.remove('has-error');live.textContent='Gespeichert.';setTimeout(()=>{if(live.textContent==='Gespeichert.')live.textContent='';},3000);}catch(err){error.textContent=err.message;error.focus();}finally{busy=false;form.removeAttribute('aria-busy');save.textContent='Speichern';form.querySelectorAll('button,input,textarea,select').forEach(el=>el.disabled=false);document.getElementById('manage-close').disabled=false;lockRelations();}}
 form.addEventListener('submit',event=>{event.preventDefault();if(form.dataset.mode==='detail')return;const data=Object.fromEntries(new FormData(form));for(const key of ['amount','price','latitude','longitude','totalBudget','guests'])if(key in data)data[key]=data[key]===''?null:Number(data[key]);if(data.currency)data.currency=data.currency.toUpperCase();if(kind==='drone')data.favorite=form.elements.favorite.checked;perform(()=>{if(kind==='budget')return repo.saveBudget(data);const saved=repo.save(kind,data,item.id);if(kind==='booking'&&saved&&(saved.totalAmount!=null||saved.price!=null)){try{repo.expenseFrom('booking',saved.id);}catch(e){}}return saved;});});
 function close(){if(!busy)dialog.close();}document.getElementById('manage-close').onclick=close;document.getElementById('manage-cancel').onclick=close;dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});dialog.addEventListener('close',()=>opener?.focus());
 function confirmDelete(){const confirm=document.getElementById('manage-confirm');document.getElementById('manage-confirm-text').textContent=kind==='activity'&&item.stopId?'Dieser Ausflug wird auch aus dem Tagesplan entfernt. Verknüpfte Buchungen und Ausgaben bleiben erhalten.':'Diesen Eintrag löschen? Verknüpfte Datensätze bleiben erhalten.';confirm.showModal();document.getElementById('manage-confirm-no').onclick=()=>confirm.close();document.getElementById('manage-confirm-yes').onclick=()=>{confirm.close();perform(()=>{if(kind==='booking'){const linkedExp=repo.get('expense').find(e=>e.bookingId===item.id);if(linkedExp){try{repo.remove('expense',linkedExp.id);}catch(e){}}}return repo.remove(kind,item.id);});};}
 del.onclick=confirmDelete;
 detailActions.onclick=event=>{const cmd=event.target.closest('[data-detail]')?.dataset.detail;if(cmd==='edit')open(kind,item);if(cmd==='delete')confirmDelete();if(cmd==='duplicate')perform(()=>repo.duplicateActivity(item.id));if(cmd==='expense')perform(()=>repo.expenseFrom(kind,item.id));if(cmd==='map'||cmd==='day'){dialog.close();root.ManagementPage.openDay(item,cmd==='map');}};
 function detail(type,entity){open(type,entity,true);detailActions.innerHTML=U.action('Bearbeiten','unused') .replace('data-manage="unused"','data-detail="edit"')+`<button type="button" class="trip-danger-button glass-pill glass-action-danger" data-detail="delete">Löschen</button>`+(['activity','booking'].includes(type)?`<button type="button" class="trip-secondary-button glass-pill" data-detail="expense">Ausgabe erfassen</button>`:'')+(type==='activity'?`<button type="button" class="trip-secondary-button glass-pill" data-detail="duplicate">Duplizieren</button>`:'')+(entity.dayId?`<button type="button" class="trip-secondary-button glass-pill" data-detail="day">Zum Tagesplan</button>`:'')+(entity.stopId?`<button type="button" class="trip-secondary-button glass-pill" data-detail="map">Auf Karte anzeigen</button>`:'');}
 return {open,detail};
}
root.createManagementEditor=createEditor;
}(window));
