(function(root){
'use strict';const M=root.TripModel,N=root.ManagementModel,U=root.ManagementUI,e=M.escape;
let repo,editor,ready=false;
const filters=Object.fromEntries(['expense','activity','booking','document'].map(k=>[k,{category:'all',query:'',status:'all'}]));
const targets={finance:document.getElementById('manage-finance'),expenses:document.getElementById('manage-expenses'),activity:document.getElementById('manage-activities'),booking:document.getElementById('manage-bookings'),document:document.getElementById('manage-documents')};
function sorted(items){return items.sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')||(a.startTime||'').localeCompare(b.startTime||''));}
function filtered(kind){const f=filters[kind];return sorted(repo.get(kind).filter(x=>(f.category==='all'||(kind==='booking'?x.type:x.category)===f.category)&&(f.status==='all'||x.status===f.status)&&[x.title,x.provider,x.location,x.locationName,x.notes,x.bookingReference].join(' ').toLowerCase().includes(f.query.toLowerCase())));}
function listContent(kind,items){return items.length?U.list(kind,items,repo,kind==='expense'?root.FinanceView.divisor():1):U.empty(kind,repo.get(kind).length>0);}
function renderKind(kind){const f=filters[kind],items=filtered(kind);let html='';
 if(kind==='expense'){const controls=U.filters(kind,N.CATEGORIES,f.category,f.query,f.status),content=listContent(kind,items);document.getElementById('finance-scope-controls').innerHTML=root.FinanceView.toggle();targets.finance.innerHTML=U.finance(repo,repo.get(kind))+controls+content;targets.expenses.innerHTML=U.header('Ausgaben','Jeder Betrag an seinem Platz.','expense')+controls+content;return;}
 if(kind==='activity')html=U.header('Ausflüge','Plane Aktivitäten und besondere Erlebnisse.','activity')+U.filters(kind,N.ACTIVITY_CATEGORIES,f.category,f.query)+(items.length?U.cards(items,repo):U.empty(kind,repo.get(kind).length>0));
 if(kind==='booking'){const badge=document.getElementById('org-badge-bookings-count');if(badge)badge.textContent=String(repo.get('booking').length);}
 if(kind==='booking')html=U.header('Buchungen','Alle Reservierungen an einem Ort.','booking')+U.bookingSummary(repo.get(kind))+U.filters(kind,N.BOOKING_TYPES,f.category,f.query,f.status)+listContent(kind,items);
 if(kind==='document')html=U.header('Dokumente','Links zu deinen Reiseunterlagen.','document')+(items.length?`<div class="glass-list">${items.map(x=>U.row({title:x.title,subtitle:N.DOCUMENT_CATEGORIES[x.category]||x.category,icon:'fa-file',attributes:`data-manage="detail" data-kind="document" data-id="${e(x.id)}"`,tail:U.dayLink(x,repo)})).join('')}</div>`:U.empty(kind));
 targets[kind].innerHTML=html;
}
function dashboard(){const title=document.getElementById('cockpit-next-title');const d=repo.trip.getDays().find(d=>d.date>=new Date().toISOString().slice(0,10))||repo.trip.getDays()[0];if(title){title.textContent=d?'Tag '+(repo.trip.getDays().findIndex(day=>day.id===d.id)+1)+': '+d.title:'Noch kein Reisetag geplant';const btn=document.getElementById('dock-next-event-btn');if(btn){btn.onclick=()=>d&&openDay({dayId:d.id});}}}
function render(){if(!ready)return;['expense','activity','booking','document'].forEach(renderKind);dashboard();window.dispatchEvent(new Event('management:changed'));if(root.buildGlobalSearchIndex)root.buildGlobalSearchIndex();}
function error(err){const el=document.getElementById('manage-live');el.textContent=err.message||String(err);el.classList.add('has-error');}
function openDay(entity,focus=false){const stop=entity.stopId?repo.trip.getStop(entity.stopId):null;const d=repo.trip.getDays().find(x=>x.id===(stop?.dayId||entity.dayId));if(!d){error(new Error('Verknüpfter Reisetag nicht mehr vorhanden.'));return;}root.showView('reise');root.TripPage.selectDayNumber(d.dayNumber);if(focus&&stop)root.TripPage.selectStop(stop.id);const target=document.getElementById(stop?'trip-stop-'+stop.id:'trip-day-'+d.id)||document.getElementById('day-'+d.dayNumber);if(target)target.scrollIntoView({behavior:'smooth',block:'center'});}
function navigate(route,sub){root.Router.navigate(route,{sub});}
function openEntity(kind,id){const entity=repo.get(kind).find(x=>x.id===id);if(!entity){error(new Error('Eintrag nicht mehr vorhanden.'));return;}navigate({expense:'finanzen',booking:'organisation',activity:'erlebnisse',drone:'mehr',document:'organisation'}[kind],{expense:'expenses',booking:'bookings',activity:'activities',drone:'drone',document:'documents'}[kind]);editor.detail(kind,entity);const target=document.getElementById('manage-editor')||targets[kind];if(target)target.scrollIntoView({behavior:'smooth',block:'center'});}
function routeSub(detail){const {route,sub}=detail;const key=(sub||'').split('/')[0];if(route==='finanzen'&&document.getElementById('fin-panel-'+key))root.switchFinTab(key);if(route==='organisation'&&['bookings','packing','documents'].includes(key))root.switchOrgTab(key);if(route==='erlebnisse'&&document.getElementById('exp-panel-'+key))root.switchExpTab(key);if(route==='mehr'&&document.getElementById('more-panel-'+key))root.switchMoreTab(key);}
function syncLayout(){const active=['finanzen','organisation','erlebnisse','mehr'].some(k=>document.getElementById('view-'+k).classList.contains('active'));document.body.classList.toggle('is-management',active);if(active)document.documentElement.style.setProperty('--management-header-height',document.querySelector('.app-header').getBoundingClientRect().height+'px');}
document.addEventListener('click',event=>{const scope=event.target.closest('[data-finance-mode]');if(scope&&ready){root.FinanceView.setMode(scope.dataset.financeMode);renderKind('expense');root.renderFuel?.();root.renderGroceries?.();root.updateOnsiteSpendMetrics?.();document.querySelector('[data-finance-mode="'+root.FinanceView.getMode()+'"]').focus();return;}const target=event.target.closest('[data-manage]');if(!target||!ready)return;const {manage:act,kind,id}=target.dataset;try{switch(act){case'create':editor.open(kind,{category:kind==='drone'?'landscape':kind==='document'?'other':kind==='expense'?'other':'sightseeing'});break;case'detail':editor.detail(kind,repo.get(kind).find(x=>x.id===id));break;case'budget':editor.open('budget',repo.getBudget());break;case'filter':if(kind==='packing'){root.filterPackingByCategory(id);}else{filters[kind].category=id;renderKind(kind);}break;case'reset':filters[kind]={category:'all',query:'',status:'all'};renderKind(kind);break;case'day':openDay({dayId:id});break;}}catch(err){error(err);}});
document.addEventListener('input',event=>{const kind=event.target.dataset.search;if(!kind||!ready||!filters[kind])return;filters[kind].query=event.target.value;const cursor=event.target.selectionStart,container=event.target.closest('.manage-page');renderKind(kind);const input=container.querySelector('[data-search]');input.focus();try{input.setSelectionRange(cursor,cursor);}catch{};});
document.addEventListener('change',event=>{const kind=event.target.dataset.statusFilter;if(kind&&filters[kind]){filters[kind].status=event.target.value;renderKind(kind);}});
window.addEventListener('app:route-changed',event=>{syncLayout();routeSub(event.detail);});window.addEventListener('resize',syncLayout);new MutationObserver(syncLayout).observe(document.body,{attributes:true,attributeFilter:['class']});
root.ManagementPage={openDay,openEntity,filterBookings(category){filters.booking.category=category;renderKind('booking');},repo:null,searchIndex(){if(!ready)return [];const entries=[];const trip=repo.trip.getTrip();if(trip)entries.push({id:trip.id,cat:'days',catLabel:'Reise',title:trip.title,subtitle:'Gesamte Reise',keywords:'trip reise',icon:'fa-map',action:()=>root.showView('reise')});repo.trip.getDays().forEach((d,i)=>entries.push({id:d.id,cat:'days',catLabel:'Tag',title:'Tag '+(i+1)+': '+d.title,subtitle:M.dateLabel(d.date),keywords:d.summary||'',icon:'fa-calendar',action:()=>openDay({dayId:d.id})}));repo.trip.getStops().forEach(s=>entries.push({id:s.id,cat:'activities',catLabel:'Stopp',title:s.title,subtitle:s.locationName||'',keywords:s.notes||'',icon:'fa-location-dot',action:()=>openDay({stopId:s.id},true)}));['expense','activity','booking','document'].forEach(kind=>repo.get(kind).forEach(x=>entries.push({id:x.id,cat:{expense:'expenses',activity:'activities',booking:'bookings',drone:'drone',document:'docs'}[kind],catLabel:{expense:'Ausgabe',activity:'Ausflug',booking:'Buchung',drone:'Drohnen-Spot',document:'Dokument'}[kind],title:x.title,subtitle:[x.date,x.locationName,x.provider].filter(Boolean).join(' · '),keywords:[x.notes,x.bookingReference].filter(Boolean).join(' '),icon:'fa-circle-dot',action:()=>openEntity(kind,x.id)})));return entries;},related(stopId){if(!ready)return '';return ['booking','expense'].flatMap(kind=>repo.get(kind).filter(x=>x.stopId===stopId).map(x=>U.action(({booking:'Buchung',expense:'Ausgabe',drone:'Drohnen-Spot'}[kind])+': '+x.title,'detail',kind,x.id,'manage-link'))).join('');}};
const viewObserver=new MutationObserver(syncLayout);
for(const key of ['finanzen','organisation','erlebnisse','mehr'])viewObserver.observe(document.getElementById('view-'+key),{attributes:true,attributeFilter:['class']});
const originalShowView=root.showView;
root.showView=function(name,skipHistory){
 originalShowView(name,skipHistory);
 if(!skipHistory&&root.Router){
  const route=root.Router.getCurrentRoute(),prefix={finanzen:'fin',organisation:'org',erlebnisse:'exp',mehr:'more'}[route];
  if(prefix){const button=document.querySelector(prefix==='org'?'#organization .org-tab-btn.active':'.'+prefix+'-subnav-btn.active');const sub=prefix==='org'?button?.id.replace('org-tab-btn-',''):button?.dataset.tab;if(sub){history.replaceState({route,sub},document.title,root.Router.routeUrl(route,sub));}}
 }
 syncLayout();
};
// Preserve the established subtab handlers and persist subtab selection in history.
for(const [name,route,prefix] of [['switchFinTab','finanzen','fin'],['switchExpTab','erlebnisse','exp'],['switchMoreTab','mehr','more'],['switchOrgTab','organisation','org']]){
 const previous=root[name];
 root[name]=function(key){
  if(prefix==='org'){
   document.querySelectorAll('#organization>.org-tab-panel').forEach(panel=>{panel.style.display=panel.id==='org-panel-'+key?'block':'none';});
   document.querySelectorAll('#organization .org-tab-btn').forEach(button=>{const active=button.id==='org-tab-btn-'+key;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));});
   if(key==='packing')root.renderPackingList();
  }else previous(key);
  if(root.Router.getCurrentRoute()===route&&location.hash!==root.Router.routeUrl(route,key))root.Router.navigate(route,{sub:key,silent:true});

 };
}
async function init(){try{const trip=root.createTripRepository(root.TripStore,root.localStorage,root.TRIP_MASTER_DATA);repo=root.createManagementRepository(trip,root.localStorage,root.ManagementLegacy);await repo.init();root.ManagementPage.repo=repo;editor=root.createManagementEditor(repo,(result,kind)=>{if(kind==='expense'&&result)openEntity('expense',result.id);});ready=true;repo.subscribe(render);render();syncLayout();routeSub(root.Router.resolveRoute());}catch(err){error(err);Object.values(targets).forEach(el=>el.innerHTML='<div class="manage-empty glass-card"><h3>Daten konnten nicht geladen werden.</h3><p>Deine gespeicherten Daten bleiben erhalten. Lade die Seite erneut.</p><button type="button" class="trip-secondary-button glass-pill" onclick="location.reload()">Erneut laden</button></div>');}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
}(window));
