(function(root){
'use strict';
const M=root.TripModel,N=root.ManagementModel,e=M.escape;
const money=(n,c='EUR')=>new Intl.NumberFormat('de-AT',{style:'currency',currency:c,maximumFractionDigits:2}).format(n||0);
const action=(label,act,kind='',id='',style='trip-secondary-button')=>`<button type="button" class="glass-pill ${style} ${style==='trip-primary-button'?'glass-action-primary':''}" data-manage="${act}" data-kind="${kind}" data-id="${e(id)}">${e(label)}</button>`;
const badge=(status,labels=N.STATUS)=>`<span class="manage-badge ${e(status)} glass-pill">${e(labels[status]||status||'Offen')}</span>`;
function header(title,text,kind){return `<div class="manage-header glass-section-heading"><div><span class="trip-eyebrow glass-eyebrow">DEINE REISE, GUT ORGANISIERT</span><h2>${e(title)}</h2><p>${e(text)}</p></div>${action('+ '+({expense:'Ausgabe',activity:'Ausflug',booking:'Buchung',drone:'Drohnen-Spot',document:'Dokument'}[kind]||'' )+' hinzufügen','create',kind,'','trip-primary-button')}</div>`;}
function filters(kind,categories,current,query,status='all'){return `<div class="glass-toolbar"><label class="glass-search"><i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i><input type="search" data-search="${kind}" value="${e(query)}" placeholder="${kind==='activity'?'Ausflüge':kind==='packing'?'Packliste':'Einträge'} suchen" aria-label="${kind==='activity'?'Ausflüge':kind==='packing'?'Packliste':'Einträge'} suchen"></label>${['booking','expense','packing'].includes(kind)?`<select data-status-filter="${kind}" aria-label="Nach Status filtern"><option value="all">Alle Status</option>${Object.entries(kind==='packing'?{open:'Noch offen',packed:'Gepackt'}:kind==='expense'?N.EXP_STATUS:N.STATUS).map(([k,v])=>`<option value="${k}" ${status===k?'selected':''}>${v}</option>`).join('')}</select>`:''}</div><div class="glass-filter-bar" aria-label="Kategorien">${Object.entries({all:'Alle',...categories}).map(([key,label])=>`<button type="button" class="trip-day-pill ${key===current?'is-active':''} glass-pill" data-manage="filter" data-kind="${kind}" data-id="${key}" aria-pressed="${key===current}">${label}</button>`).join('')}</div>`;}
function empty(kind,filtered=false){return `<div class="glass-empty glass-card"><span class="trip-eyebrow glass-eyebrow">RAUM FÜR DEINE PLÄNE</span><h3>${filtered?'Keine passenden Einträge.':{expense:'Noch keine Ausgaben erfasst.',activity:'Noch keine Ausflüge geplant.',booking:'Noch keine Buchungen hinterlegt.',drone:'Noch keine Drohnen-Spots gespeichert.',document:'Noch keine Dokumente hinterlegt.'}[kind]}</h3><p>${filtered?'Passe deine Suche oder Filter an.':'Alles beginnt mit dem ersten Eintrag.'}</p>${action(filtered?'Filter zurücksetzen':{expense:'Erste Ausgabe hinzufügen',activity:'Ausflug hinzufügen',booking:'Buchung hinzufügen',drone:'Ersten Spot hinzufügen',document:'Dokument hinzufügen'}[kind],filtered?'reset':'create',kind,'','trip-primary-button')}</div>`;}
function dayLink(item,repo){const day=repo.trip.getDays().find(d=>d.id===item.dayId);return day?action('Tag '+(repo.trip.getDays().findIndex(d=>d.id===day.id)+1),'day','',day.id,'manage-link'):item.relationMissing?'<span class="manage-muted">Verknüpfung nicht mehr vorhanden</span>':'<span class="manage-muted">Noch keinem Tag zugeordnet</span>';}
// Both bookings and packing use this exact DOM structure.
function row({id='',title,subtitle='',icon='fa-ticket',attributes='',tail='',interactive=true}){
 const tag=interactive?'button':'div';
 return `<div class="glass-row-item"${id?` id="${e(id)}"`:''}><${tag} ${interactive?'type="button" ':''}class="glass-row-main" ${attributes}><span class="glass-row-icon"><i class="fa-solid ${e(icon)}" aria-hidden="true"></i></span><span class="glass-row-copy"><strong>${e(title)}</strong><small>${e(subtitle)}</small></span></${tag}><div class="glass-row-tail">${tail}</div></div>`;
}
function list(kind,items,repo,divisor=1){
 if(!items.length)return empty(kind);let last='';
 return `<div class="glass-list">${items.map(item=>{
  const date=item.date||'',heading=date!==last?`<h3 class="glass-group-title">${e(M.dateLabel(date))}</h3>`:'';last=date;
  const amount=kind==='expense'?item.amount:(item.totalAmount??item.price);
  return heading+row({title:item.title,subtitle:kind==='expense'?N.CATEGORIES[item.category]:[item.startTime,N.BOOKING_TYPES[item.type],item.provider||item.location].filter(Boolean).join(' · '),icon:kind==='expense'?'fa-receipt':{flight:'fa-plane',hotel:'fa-bed',rentalcar:'fa-car',train:'fa-train'}[item.type]||'fa-ticket',attributes:`data-manage="detail" data-kind="${kind}" data-id="${e(item.id)}"`,tail:(amount!=null?`<strong>${e(money(amount/divisor,item.currency))}</strong>`:'')+badge(item.status,kind==='packing'?{open:'Noch offen',packed:'Gepackt'}:kind==='expense'?N.EXP_STATUS:N.STATUS)+dayLink(item,repo)});
 }).join('')}</div>`;
}
function cards(items,repo){return `<div class="manage-activity-grid">${items.map(a=>`<article class="manage-activity glass-card"><button class="manage-activity-main" type="button" data-manage="detail" data-kind="activity" data-id="${e(a.id)}">${M.safeUrl(a.image)?`<img src="${e(a.image)}" alt="" loading="lazy" onerror="this.hidden=true">`:`<div class="manage-image-placeholder"><i class="fa-solid fa-${{nature:'leaf',hiking:'mountain-sun',food:'utensils',adventure:'person-hiking'}[a.category]||'compass'}" aria-hidden="true"></i><span>${e(N.ACTIVITY_CATEGORIES[a.category])}</span></div>`}<div><span class="trip-eyebrow glass-eyebrow">${e(N.ACTIVITY_CATEGORIES[a.category]||'Ausflug')}</span><h3>${e(a.title)}</h3><p>${e([a.locationName,M.dateLabel(a.date),a.startTime].filter(Boolean).join(' · '))}</p><small>${a.startTime&&a.endTime?e(a.startTime+' – '+a.endTime):'Zeit noch offen'}${a.price!=null?' · '+e(money(a.price,a.currency)):''}</small></div></button><footer>${dayLink(a,repo)}${badge(a.bookingStatus)}</footer></article>`).join('')}</div>`;}
function finance(repo,expenses){return root.FinanceView.render(repo,expenses);}
function bookingSummary(items){return `<div class="manage-booking-summary glass-card"><strong>${items.length} Buchungen</strong>${['confirmed','pending','cancelled','completed'].map(s=>`<span>${items.filter(x=>x.status===s).length} ${N.STATUS[s].toLowerCase()}</span>`).join('')}</div>`;}
root.ManagementUI={row,money,action,badge,header,filters,empty,dayLink,list,cards,finance,bookingSummary};
}(window));
