(function(root){
'use strict';
const M=root.TripModel,N=root.ManagementModel,e=M.escape;
const money=(n,c='EUR')=>new Intl.NumberFormat('de-AT',{style:'currency',currency:c,maximumFractionDigits:2}).format(n||0);
const action=(label,act,kind='',id='',style='trip-secondary-button')=>`<button type="button" class="${style}" data-manage="${act}" data-kind="${kind}" data-id="${e(id)}">${e(label)}</button>`;
const badge=(status,labels=N.STATUS)=>`<span class="manage-badge ${e(status)}">${e(labels[status]||status||'Offen')}</span>`;
function header(title,text,kind){return `<div class="manage-header"><div><span class="trip-eyebrow">DEINE REISE, GUT ORGANISIERT</span><h2>${e(title)}</h2><p>${e(text)}</p></div>${action('+ '+({expense:'Ausgabe',activity:'Ausflug',booking:'Buchung',drone:'Drohnen-Spot',document:'Dokument'}[kind]||'' )+' hinzufügen','create',kind,'','trip-primary-button')}</div>`;}
function filters(kind,categories,current,query,status='all'){return `<div class="manage-toolbar"><label class="manage-search"><i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i><input type="search" data-search="${kind}" value="${e(query)}" placeholder="${kind==='activity'?'Ausflüge':'Einträge'} suchen" aria-label="${kind==='activity'?'Ausflüge':'Einträge'} suchen"></label>${['booking','expense'].includes(kind)?`<select data-status-filter="${kind}" aria-label="Nach Status filtern"><option value="all">Alle Status</option>${Object.entries(kind==='expense'?N.EXP_STATUS:N.STATUS).map(([k,v])=>`<option value="${k}" ${status===k?'selected':''}>${v}</option>`).join('')}</select>`:''}</div><div class="manage-filters" aria-label="Kategorien">${Object.entries({all:'Alle',...categories}).map(([key,label])=>`<button type="button" class="trip-day-pill ${key===current?'is-active':''}" data-manage="filter" data-kind="${kind}" data-id="${key}" aria-pressed="${key===current}">${label}</button>`).join('')}</div>`;}
function empty(kind,filtered=false){return `<div class="manage-empty trip-glass"><span class="trip-eyebrow">RAUM FÜR DEINE PLÄNE</span><h3>${filtered?'Keine passenden Einträge.':{expense:'Noch keine Ausgaben erfasst.',activity:'Noch keine Ausflüge geplant.',booking:'Noch keine Buchungen hinterlegt.',drone:'Noch keine Drohnen-Spots gespeichert.',document:'Noch keine Dokumente hinterlegt.'}[kind]}</h3><p>${filtered?'Passe deine Suche oder Filter an.':'Alles beginnt mit dem ersten Eintrag.'}</p>${action(filtered?'Filter zurücksetzen':{expense:'Erste Ausgabe hinzufügen',activity:'Ausflug hinzufügen',booking:'Buchung hinzufügen',drone:'Ersten Spot hinzufügen',document:'Dokument hinzufügen'}[kind],filtered?'reset':'create',kind,'','trip-primary-button')}</div>`;}
function dayLink(item,repo){const day=repo.trip.getDays().find(d=>d.id===item.dayId);return day?action('Tag '+(repo.trip.getDays().findIndex(d=>d.id===day.id)+1),'day','',day.id,'manage-link'):item.relationMissing?'<span class="manage-muted">Verknüpfung nicht mehr vorhanden</span>':'<span class="manage-muted">Noch keinem Tag zugeordnet</span>';}
function list(kind,items,repo){if(!items.length)return empty(kind);let last='';return `<div class="manage-list trip-glass">${items.map(item=>{const date=item.date||'';const dateHeading=date!==last?`<h3 class="manage-date">${e(M.dateLabel(date))}</h3>`:'';last=date;const amount=kind==='expense'?item.amount:item.price;return `${dateHeading}<div class="manage-row"><button type="button" class="manage-row-main" data-manage="detail" data-kind="${kind}" data-id="${e(item.id)}"><span class="manage-row-icon"><i class="fa-solid ${kind==='expense'?'fa-receipt':{flight:'fa-plane',hotel:'fa-bed',rentalcar:'fa-car',train:'fa-train'}[item.type]||'fa-ticket'}" aria-hidden="true"></i></span><span><strong>${e(item.title)}</strong><small>${e(kind==='expense'?N.CATEGORIES[item.category]:[item.startTime,N.BOOKING_TYPES[item.type],item.provider||item.location].filter(Boolean).join(' · '))}</small></span></button><div class="manage-row-tail">${amount!=null?`<strong>${e(money(amount,item.currency))}</strong>`:''}${badge(item.status,kind==='expense'?N.EXP_STATUS:N.STATUS)}${dayLink(item,repo)}</div></div>`;}).join('')}</div>`;}
function cards(items,repo){return `<div class="manage-activity-grid">${items.map(a=>`<article class="manage-activity trip-glass"><button class="manage-activity-main" type="button" data-manage="detail" data-kind="activity" data-id="${e(a.id)}">${M.safeUrl(a.image)?`<img src="${e(a.image)}" alt="" loading="lazy" onerror="this.hidden=true">`:`<div class="manage-image-placeholder"><i class="fa-solid fa-${{nature:'leaf',hiking:'mountain-sun',food:'utensils',adventure:'person-hiking'}[a.category]||'compass'}" aria-hidden="true"></i><span>${e(N.ACTIVITY_CATEGORIES[a.category])}</span></div>`}<div><span class="trip-eyebrow">${e(N.ACTIVITY_CATEGORIES[a.category]||'Ausflug')}</span><h3>${e(a.title)}</h3><p>${e([a.locationName,M.dateLabel(a.date),a.startTime].filter(Boolean).join(' · '))}</p><small>${a.startTime&&a.endTime?e(a.startTime+' – '+a.endTime):'Zeit noch offen'}${a.price!=null?' · '+e(money(a.price,a.currency)):''}</small></div></button><footer>${dayLink(a,repo)}${badge(a.bookingStatus)}</footer></article>`).join('')}</div>`;}
function finance(repo,expenses){const s=repo.summary(),pct=s.totalBudget?Math.round(s.spent/s.totalBudget*100):0;return `${header('Finanzen','Behalte deine Reisekosten im Blick.','expense')}<div class="manage-summary">${[['Gesamtbudget',s.totalBudget],['Ausgegeben',s.spent],['Verbleibend',s.remaining]].map(([title,n])=>`<div class="trip-glass manage-summary-card"><span>${title}</span><strong>${e(money(n,s.currency))}</strong></div>`).join('')}</div><div class="manage-finance-grid"><section class="trip-glass manage-budget"><div class="manage-section-heading"><h3>Dein Budget</h3>${action('Budget bearbeiten','budget')}</div><strong>${e(money(s.spent,s.currency))} <span>/ ${e(money(s.totalBudget,s.currency))}</span></strong><div class="manage-progress" role="progressbar" aria-label="Verwendetes Budget" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.min(100,pct)}" aria-valuetext="${pct} Prozent verwendet"><span style="width:${Math.min(100,pct)}%"></span></div><p>${s.totalBudget?`${pct} % verwendet`:'Lege dein Reisebudget fest.'}${s.pending?' · '+e(money(s.pending,s.currency))+' offen':''}</p>${s.excluded?`<p class="manage-notice">${s.excluded} Ausgabe(n) in anderen Währungen separat gelistet. Keine automatische Umrechnung.</p>`:''}<small>Budget und Ausgaben gelten für die gesamte Reisegruppe.</small></section><section class="trip-glass manage-categories"><h3>Wofür du Geld ausgibst</h3>${s.categories.filter(c=>c.amount).map(c=>`<div><span>${N.CATEGORIES[c.category]}</span><strong>${e(money(c.amount,s.currency))}</strong></div>`).join('')||'<p>Noch keine bezahlten Ausgaben.</p>'}</section></div><div class="manage-section-heading"><h3>Deine Ausgaben</h3><span class="manage-muted">${expenses.length} Einträge</span></div>`;}
function bookingSummary(items){return `<div class="manage-booking-summary trip-glass"><strong>${items.length} Buchungen</strong>${['confirmed','pending','cancelled','completed'].map(s=>`<span>${items.filter(x=>x.status===s).length} ${N.STATUS[s].toLowerCase()}</span>`).join('')}</div>`;}
root.ManagementUI={money,action,badge,header,filters,empty,dayLink,list,cards,finance,bookingSummary};
}(window));
